<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>KairosoftGameToolbox</RootNamespace>
    <AssemblyName>KairosoftGameToolbox.Core</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

</Project>
